### ISSUE TITLE
Support TTS

### ISSUE THREAD

**Issue by jubalh** [LuteOrg/lute-v3#412] opened 2024-05-07 21:54 UTC
**Is your feature request related to a problem? Please describe.**

When I select a word and press `t` it nicely opens DeepL to translate the whole sentence for me.
Similarly I would like to press `p` (for play) to listen to the whole sentence.

**Describe the solution you'd like**

Anki has an [TTS addon](https://github.com/AwesomeTTS/awesometts-anki-addon) and I assume we could use the same services/method they are using, it seems to work quite reliable.
Their list of supported services is [here](https://github.com/AwesomeTTS/awesometts-anki-addon/wiki/Current-Status-of-Services-and-Voices).

**Describe alternatives you've considered**

For now I have just added Yandex as dictionary that opens in a popup. I then click the sound button there. But it's a few steps too many to be comfortable to use.

**Comment by jzohrab** [comment] 2024-05-07 22:01
Duplicate of #36, closing.  Thanks @jubalh

**Closed by jzohrab** 2024-05-07 22:01 UTC
Labels: duplicate

**Comment by jubalh** [comment] 2024-05-07 22:11
Strange! I actually searched for `tts` before opening. Not sure what went wrong :)

**Comment by jzohrab** [comment] 2024-05-07 22:23
I just added TTS to the title, it wasn’t there before. Updated it after your question 🙂
