### ISSUE TITLE
Parent status link bugs - No2 "Parent lost all their kids"

### ISSUE THREAD

**Issue by LangNerd23** [LuteOrg/lute-v3#417] opened 2024-05-13 19:28 UTC
**Description**

There is a special situation I encounter sometimes, that destroys some of my data, more specifically all children loose their connection to the parent. 
(Maybe related to „parent status link bugs – No1“ [that I had posted before](https://github.com/LuteOrg/lute-v3/issues/416))

**To Reproduce**

1. Choose a term that has no parent yet (and has status 1)
2. Go into edit mode
3. Choose a parent from drop down list; choose a term as parent that has already a couple of children with all of them with status_linked yes (in my case these were usually words I had as WellKnown, but probably doesn’t matter)
4. After having picked the new parent the box status_link had been automatically checked
5. Unselect the checkbox
6. Save
7. Got to term overview and search for the selected parent term; all kids will show up with a different status now (mostly status 1); once they are opened, „link to parent“ is unchecked

A variation of this error has been observed when deleting a non-linked parent from a term. Also in that moment it had happened that the parent lost its other kids. 

**Extra software info, if not already included in the Description:**

- OS: Windows
- Browser: Checked both with Chrome and Firefox
- How you've installed Lute (Docker, python, source): via pip, Version 3.3.2 (couldn’t check with 3.3.3 for the reasons given on discord)

**Comment by jzohrab** [comment] 2024-05-13 19:38
Thanks very much!  Will try to reproduce.

**Comment by jzohrab** [comment] 2024-05-14 00:22
Attempt 1: Unable to reproduce, on chrome:

"when" is parent to "the" and "form", "pops" doesn't have a parent yet.

> <img width="232" alt="image" src="https://github.com/LuteOrg/lute-v3/assets/1637133/a2616efd-9968-4f3a-b093-2a3bf252a921">

Added "when" as parent to "pops", unchecked the box.  On save, everything that was linked before still is.

> <img width="238" alt="image" src="https://github.com/LuteOrg/lute-v3/assets/1637133/cb185007-08f8-4b88-8f98-19b32b8c6aed">

I'll try again with setting the child statuses to well-known.

**Comment by jzohrab** [comment] 2024-05-14 03:44
Attempt 2, not able to reproduce:

"these" is parent of the other terms next to it, all well-known, the last term is status 1, added "these" parent, deselected checkbox, just before save:

> <img width="213" alt="image" src="https://github.com/LuteOrg/lute-v3/assets/1637133/decae5a7-e50d-4ef0-8ceb-97f1d454f44f">

After save, everything is as expected: previously linked still linked, new child isn't linked:

> <img width="217" alt="image" src="https://github.com/LuteOrg/lute-v3/assets/1637133/ec08c108-263e-4dfd-ad81-2fbe7cc8e1de">

**Comment by jzohrab** [comment] 2024-05-14 03:51
**Confirmed the other case, "deleting a non-linked parent from a term", unlinks the other child terms.**

he term "blue" above has non-linked parent "these", will delete the parent "these" from "blue".  "words" and "are" are both linked to parent "these".  Pre-delete is the same as above diagram.

Removing parent from "blue", about to save:

> <img width="294" alt="image" src="https://github.com/LuteOrg/lute-v3/assets/1637133/07b2db23-0881-4b17-a04c-a602c35235a0">

parent term "these" deleted from both "words" and "are":

> <img width="400" alt="image" src="https://github.com/LuteOrg/lute-v3/assets/1637133/65fc1119-d00c-4458-9718-8909bea45689">

This was also consistently reproduced: I set up the same terms and did the same things, and the other parent links were broken again.

**Comment by jzohrab** [comment] 2024-05-31 18:25
Working on a fix.  Repeated the above scenario: unlinked parent "these" removed from term "blue", and the other terms that had that parent maintained the existing link:

> ![Image](https://github.com/LuteOrg/lute-v3/assets/1637133/853615f9-64ca-4b76-b195-4c023dd04243)

**Comment by jzohrab** [comment] 2024-05-31 19:51
Fix merged into develop, will be in next launch.

**Comment by jzohrab** [comment] 2024-06-09 05:58
Hi @LangNerd23 -- I believe that this has been fixed with the launch of 3.4.3 (just now).  I'll close this issue -- please re-open a new one if you run into more problems with this, and reference this if needed.  Cheers and thanks!

**Closed by jzohrab** 2024-06-09 05:58 UTC
Labels: bug, fixed
